### PR TITLE
Add new fields hastag and inserted_at in sqlite table

### PR DESCRIPTION
**Pull request by lecoueyl**
### Update

@ptkdev It would be nice to also have the date time when the event is inserted in the sqlite base and the hashtag used for it.

- Add `hashtag` and `created_at` fields for users and fdf tables
- Add `compare_version()` utils
- Display more explicit output text

### What could be done

Instead of have an table for each mode, use global table `users` and `posts`
These tables could be uses for all the mode and use DRY requests

```
users
    id: INTEGER PRIMARY KEY AUTOINCREMENT,
    account: TEXT,
    username: TEXT,
    mode: TEXT,
    url: TEXT,
    hashtag: TEXT,
    action: TEXT,
    created_at: DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at: DATETIME

posts
    id: INTEGER PRIMARY KEY AUTOINCREMENT,
    account: TEXT,
    username: TEXT,
    mode: TEXT,
    url: TEXT,
    hashtag: TEXT,
    action: TEXT,
    created_at: DATETIME DEFAULT CURRENT_TIMESTAMP
```

### CODE REVIEW

**Comment by ptkdev** [comment]
# Great! 
## Bug
But this code have a bug, you need insert `ALTER TABLE <YourTable> ADD <NewColumn>` in `init_db()` if version of bot is > 0.9.0

## Why? 
If i run this patch and exist previous database (without this new column) the bot crash on all insert.

## Solution
Add `if()` in `init_db()` with `version = require("./version");` and alter table. Use try catch if column exist don't alter table give exception.

# Fix
If you fix this i merge pull request

**Comment by lecoueyl** [comment]
Thank you fro your detailed answer, I will do so

**Comment by ptkdev** [comment]
As regards the second request if you want split users table to posts table imho isn't necessary at moment. The priority is implement sql-lite in all mod. Single table at moment is ok, in future i split users table.

**Comment by lecoueyl** [comment]
I have included the `compare_version()` function in utils and use it to alter table if needed>
Hope this is what you were looking for!

**Comment by ptkdev** [comment]
@lecoueyl perfect, i test it and merge. P.s i send you invite for social-manager-tools organization membership :) Thanks for help!

**Comment by ptkdev** [comment]
@lecoueyl hi, this code don't work correctly and have a big bug: `Cannot add a column with non-constant default
`
See:
- https://stackoverflow.com/questions/11631390/how-to-add-a-date-column-to-a-table-with-current-date-as-default-value
- https://github.com/laravel/framework/issues/20747#issuecomment-325184078

## Problem
Is impossible add to `DATETIME` the `DEFAULT CURRENT_TIME` (sql-lite limits), for the old db in use i set value `NULL`. Happen :(

**Pull request merged**
